// <auto-generated />
using System;
using KreditService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KreditService.Migrations
{
    [DbContext(typeof(KreditDbContext))]
    partial class KreditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KreditService.Models.PengajuanKredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal>("Angsuran")
                        .HasColumnType("numeric")
                        .HasColumnName("angsuran");

                    b.Property<decimal>("Bunga")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("bunga");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("Plafon")
                        .HasColumnType("numeric")
                        .HasColumnName("plafon");

                    b.Property<int>("Tenor")
                        .HasColumnType("integer")
                        .HasColumnName("tenor");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("Plafon")
                        .HasDatabaseName("idx_plafon");

                    b.HasIndex("Tenor")
                        .HasDatabaseName("idx_tenor");

                    b.ToTable("pengajuan_kredit");
                });
#pragma warning restore 612, 618
        }
    }
}
